name: JotJotWidget
options:
  bundleIdPrefix: com.kenefe
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"

targets:
  JotJotWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_NAME: JotJotWidget
        PRODUCT_BUNDLE_IDENTIFIER: com.kenefe.jotjot.widget
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: "5.9"
        DEVELOPMENT_TEAM: P2GN9QW8E5
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_KEY_CFBundleDisplayName: JotJot
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
