name: JotJotMac
options:
  bundleIdPrefix: com.kenefe
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"

targets:
  JotJotMac:
    type: application
    platform: macOS
    sources:
      - path: Sources
      - path: ../JotJotKit/Sources
      - path: Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_NAME: JotJot
        PRODUCT_BUNDLE_IDENTIFIER: com.kenefe.jotjot
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_GENERATION_MODE: GeneratedFile
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        CODE_SIGN_ENTITLEMENTS: Resources/JotJot.entitlements
    entitlements:
      path: Resources/JotJot.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-write: true
        com.apple.developer.icloud-services:
          - CloudKit
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.kenefe.jotjot
